SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;

ALTER TABLE `orders` ADD `discount` double NOT NULL DEFAULT '0' AFTER `count`;

SET FOREIGN_KEY_CHECKS=1;
COMMIT;
