SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;

ALTER TABLE reports CHANGE id id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE dep RENAME TO journal;
ALTER TABLE `receipts` DROP `signature`;
ALTER TABLE `products` ADD `coupon` TINYINT NOT NULL DEFAULT '0' AFTER `image`;

CREATE TABLE `dep` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `receiptNum` int(11),
  `data` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

SET FOREIGN_KEY_CHECKS=1;
COMMIT;
